### ISSUE TITLE
The MockSwitch example throws an error (bad_record_mac(20)) while pairing the TestBridge device

### ISSUE THREAD

**Issue by foxuser** [beowulfe/HAP-Java#31]
13:23:28.968 [defaultEventExecutorGroup-4-1] DEBUG c.b.hap.impl.pairing.PairingManager - Entering second stage of pair for Test Bridge
13:23:29.064 [defaultEventExecutorGroup-4-1] INFO  c.b.h.i.http.HomekitClientConnection - 200 /pair-setup
13:23:29.092 [defaultEventExecutorGroup-4-1] DEBUG c.b.hap.impl.pairing.PairingManager - Entering third stage of pair for Test Bridge
13:23:29.203 [defaultEventExecutorGroup-4-1] ERROR c.b.hap.impl.pairing.PairingManager - Exception while finalizing pairing
org.bouncycastle.crypto.tls.TlsFatalAlert: bad_record_mac(20)
	at com.beowulfe.hap.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:35) ~[hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.crypto.ChachaDecoder.decodeCiphertext(ChachaDecoder.java:46) ~[hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.pairing.FinalPairHandler.decrypt(FinalPairHandler.java:43) ~[hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.pairing.FinalPairHandler.handle(FinalPairHandler.java:38) ~[hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.pairing.PairingManager.handle(PairingManager.java:59) ~[hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.connections.HttpSession.handlePairSetup(HttpSession.java:107) [hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.connections.HttpSession.handleRequest(HttpSession.java:51) [hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.doHandleRequest(ConnectionImpl.java:51) [hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.connections.ConnectionImpl.handleRequest(ConnectionImpl.java:46) [hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:50) [hap-1.1.4-SNAPSHOT.jar:na]
	at com.beowulfe.hap.impl.http.impl.AccessoryHandler.channelRead0(AccessoryHandler.java:18) [hap-1.1.4-SNAPSHOT.jar:na]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:32) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:299) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:36) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:112) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.32.Final.jar:4.0.32.Final]
	at java.lang.Thread.run(Thread.java:744) [na:1.8.0]
13:23:29.203 [defaultEventExecutorGroup-4-1] INFO  c.b.h.i.http.HomekitClientConnection - 401 /pair-setup
13:23:29.583 [defaultEventExecutorGroup-4-1] INFO  c.b.h.i.http.impl.AccessoryHandler - Terminated homekit connection from /192.168.4.102:56125

**Comment by foxuser** [comment]
the error disappeared after new checkout and rebuilding it
